#!/usr/bin/env bash
# bits v2 = the text-source search on ONE judge, identical rows - judged on critic v2's best-CALIBRATED checkpoint (step 3000, captured) instead of ckpt_final (replaces stage 6 of chain_phase1_writes.sh).
# Also runs the same three jobs on ckpt_final once it exists (checkpoint-sensitivity column). Ledger-aware; 3 x H100 per judge, launched as hf-many.
set -uo pipefail; unset MODAL_TOKEN_ID MODAL_TOKEN_SECRET; cd /home/celeste/nlt; source /home/celeste/nlt-q36-logs/gpu_lib.sh
TAG=v2; TX=/vol/q36/text/v2; TX1=/vol/q36/text/v1; LOGD=/home/celeste/nlt-q36-logs; D=/home/celeste/shared/reports/nlt-27b-olens/data
log(){ echo "[bits2] $(date -u +%H:%M) $*"; }
nfiles(){ timeout 120 modal volume ls nlt "$1" 2>/dev/null | grep -cE "$2" || true; }
run(){ if [ "${QUEUE_MODE:-0}" = 1 ]; then local k=0; while IFS= read -r piece; do k=$((k + 1)); enqueue_eval "$piece" "${2}_$k" "${PRIO:-5}"; done < <(echo "$1" | sed "s/ ;; /\n/g"); return; fi; out=$(spawn_retry env NLT_Q36_GPU=H100 timeout 900 modal run --detach scripts/modal_nlt_q36.py --task hf-many --gpus 1 --script eval_bits.py --args "$1"); echo "$out" | sed "s/^/[$2] /" | tee -a $LOGD/apps.txt; ledger_add "$out" 1 "$2"; }
jobs_for(){ CK=$1; OUT=$2
  echo "--data-dir /vol/q36/data --ckpt $CK --out /vol/q36/results/bits_${OUT}_sources.json --sets 'raw_all:$TX/val/raw_all__*.parquet,raw_all_w:$TX/val/raw_all_w__*.parquet,craft_full:$TX/val/craft_full__*.parquet,describer_A:$TX1/val/describer_sonnet5_A__*.parquet,describer_W:$TX/val/describer_sonnet5_W__*.parquet' --twins 'craft_twins:$TX/val/twins__*.parquet' --neighbors /vol/q36/data/neigh --neighbor-n 256 --n 512 --ode-steps 64 ;; --data-dir /vol/q36/data --ckpt $CK --out /vol/q36/results/bits_${OUT}_loo.json --sets 'raw_all:$TX/val/raw_all__*.parquet,raw_no_i:$TX/val/raw_no_i__*.parquet,raw_no_j:$TX/val/raw_no_j__*.parquet,raw_no_delta:$TX/val/raw_no_delta__*.parquet,raw_no_jl:$TX/val/raw_no_jl__*.parquet,raw_all_w:$TX/val/raw_all_w__*.parquet,raw_w_no_attn:$TX/val/raw_w_no_attn__*.parquet,raw_w_no_mlp:$TX/val/raw_w_no_mlp__*.parquet,writes_only:$TX/val/writes_only__*.parquet' --n 512 --ode-steps 64 --skip-samples ;; --data-dir /vol/q36/data --ckpt $CK --out /vol/q36/results/bits_${OUT}_singles.json --sets 'olens_i:$TX/val/olens_i__*.parquet,olens_j:$TX/val/olens_j__*.parquet,craft_delta:$TX/val/craft_delta__*.parquet,jlens:$TX/val/jlens__*.parquet,craft_newfaded:$TX/val/craft_newfaded__*.parquet,craft_nojl:$TX/val/craft_nojl__*.parquet' --n 512 --ode-steps 64 --skip-samples"; }
pull(){ OUT=$1; wait_bits bits_${OUT}_sources bits_${OUT}_loo bits_${OUT}_singles || return 1; for f in sources loo singles; do cp /tmp/q36_chk_bits_${OUT}_$f.json $D/bits_${OUT}_$f.json; done; log "bits_$OUT pulled"; }
# judge 1: the calibrated step-3000 checkpoint (do not wait for the RL launch: the RL launcher takes 4 of the 8, these take 3 -> wait_gpu keeps the sum <= 8)
for i in $(seq 1 400); do grep -q "bits_verb_v1b\] SPAWNED" $LOGD/apps.txt && grep -q "rl_v3\] SPAWNED" $LOGD/apps.txt && break; sleep 120; done; log "RL v3 and bits_v1b_verbalizer have their GPUs; queueing behind them"
PRIO=5 wait_gpu 3 || exit 1; run "$(jobs_for /vol/q36/critic/v2/ckpt_step3000.pt v2)" bits2_s3000
pull v2 && { timeout 120 modal volume get nlt q36/critic/v2/eval_latest.json $D/critic_v2_eval_latest.json --force >/dev/null 2>&1; systemd-run --user --scope -q -p MemoryMax=2G python3 scripts/plot_nlt_q36_phase1.py --tag v2 2>&1 | tail -3; (cd /home/celeste/shared/reports/nlt-27b-olens && systemd-run --user --scope -q -p MemoryMax=1G python3 build_html.py >/dev/null 2>&1); log "v2 (step 3000 judge) plotted + report built"; }
# judge 2: ckpt_final (sensitivity), only after the calibrated one is in
for i in $(seq 1 400); do [ "$(nfiles q36/critic/v2 'ckpt_final.pt')" -ge 1 ] && break; sleep 180; done
PRIO=5 wait_gpu 3 || exit 1; run "$(jobs_for /vol/q36/critic/v2/ckpt_final.pt v2final)" bits2_final
pull v2final; log "BITS V2 DONE"
