#!/usr/bin/env bash
# RL v4 (orchestrator 07:17) = rl_v3's recipe with the NO-UNCOND critic v1b (ckpt_best) as frozen judge AND co-trained start; policy = v1b SFT. Fires when v1b's training is done and 4 GPUs are free (cap 8).
# RL v3 = rl_v2 (auto lambda) + the target-scale fix (reward / eval on sqrt(d) u_j s, as the critic was trained) + teacher reference in the eval,
# starting from the FULL-LENGTH SFT policy v1b (256-token targets: the v1 policy never saw the Shift line) with a 208-token budget (teacher p50).
set -uo pipefail; unset MODAL_TOKEN_ID MODAL_TOKEN_SECRET; cd /home/celeste/nlt; source /home/celeste/nlt-q36-logs/gpu_lib.sh
BAND=12,16,20,24,28,30,32,36,40,42,44,48,52,54,56,60; TAG=v1; TX=/vol/q36/text/$TAG; CK=${CRITIC_CK:-/vol/q36/critic/v1b/ckpt_best.pt}; GATE_DIR=${GATE_DIR:-q36/critic/v1b}; LOGD=/home/celeste/nlt-q36-logs; RL_TAG=${RL_TAG:-rl_v4}
log(){ echo "[rl4] $(date -u +%H:%M) $*"; }
for i in $(seq 1 900); do [ "$(timeout 120 modal volume ls nlt $GATE_DIR 2>/dev/null | grep -c ckpt_final.pt)" -ge 1 ] && break; [ $((i % 10)) -eq 0 ] && log "waiting for $GATE_DIR/ckpt_final.pt (then ckpt_best is the final best)"; sleep 120; done; log "judge critic trained: $CK"
others_pending(){ echo 0; }   # RL has priority over the v1b ablation; v1b waits with its own ledger-aware guard
POL=${POLICY:-/vol/q36/verbalizer/v1b/final}; for i in $(seq 1 400); do [ "$(timeout 120 modal volume ls nlt "$(echo ${POL%/final} | sed "s|^/vol/||")" 2>/dev/null | grep -c final)" -ge 1 ] && break; [ $((i % 5)) -eq 0 ] && log "waiting for the policy $POL"; sleep 120; done; log "policy ready: $POL"
PRIO=${PRIO:-1} wait_gpu 4 || exit 1; g=$(gpus_in_use); cap=$(cap_now); log "launching RL $RL_TAG ($g in use, cap $cap, prio ${PRIO:-1})"
out=$(NLT_Q36_GPU=H200 timeout 900 modal run --detach scripts/modal_nlt_q36.py --task hf --gpus 4 --nproc 4 --script rl_verbalizer.py --args "--data-dir /vol/q36/data --policy $POL --critic $CK --frozen-critic ${FROZEN_CK:-$CK} --replay-text '$TX/train/craft_full__*.parquet,$TX/train/describer_sonnet5_A__*.parquet' --twins '$TX/val/twins__*.parquet' --ref-text '$TX/val/craft_full__*.parquet' --out /vol/q36/rl/$RL_TAG --band $BAND --max-train-pos 60000 --steps ${STEPS:-120} --batch 16 --group 8 --n-tok ${NTOK:-208} --lr 1e-5 --critic-lr 3e-5 --kl 0.02 --lam -1 --eval-every 10 --save-every 25 --heldout 128 --gen-chunk 32 --bwd-chunk 2 --no-grad-ckpt --wandb-name $RL_TAG" 2>&1 | grep -E "SPAWNED|modal.com/apps|Error|rror:")
echo "$out" | sed "s/^/[$RL_TAG] /" | tee -a $LOGD/apps.txt; ledger_add "$out" 4 $RL_TAG; echo "$out" | grep -oE "ap-[A-Za-z0-9]+" | head -1 > $LOGD/rl_app_$RL_TAG.txt; log "RL app $(cat $LOGD/rl_app_$RL_TAG.txt)"
